// IT IS GENERATED BY FLR - DO NOT MODIFY BY HAND
// YOU CAN GET MORE DETAILS ABOUT FLR FROM:
// - https://github.com/Fly-Mix/flr-cli
// - https://github.com/Fly-Mix/flr-vscode-extension
// - https://github.com/Fly-Mix/flr-as-plugin
//

// ignore: unused_import
import 'package:flutter/widgets.dart';
// ignore: unused_import
import 'package:flutter/services.dart' show rootBundle;
// ignore: unused_import
import 'package:path/path.dart' as path;
// ignore: unused_import
import 'package:flutter_svg/flutter_svg.dart';
// ignore: unused_import
import 'package:r_dart_library/asset_svg.dart';

/// This `R` class is generated and contains references to static asset resources.
class R {
  /// package name: covid_info
  static const package = "covid_info";

  /// This `R.image` struct is generated, and contains static references to static non-svg type image asset resources.
  static const image = _R_Image();

  /// This `R.svg` struct is generated, and contains static references to static svg type image asset resources.
  static const svg = _R_Svg();

  /// This `R.text` struct is generated, and contains static references to static text asset resources.
  static const text = _R_Text();

  /// This `R.fontFamily` struct is generated, and contains static references to static font asset resources.
  static const fontFamily = _R_FontFamily();
}

/// Asset resource’s metadata class.
/// For example, here is the metadata of `packages/flutter_demo/assets/images/example.png` asset:
/// - packageName：flutter_demo
/// - assetName：assets/images/example.png
/// - fileDirname：assets/images
/// - fileBasename：example.png
/// - fileBasenameNoExtension：example
/// - fileExtname：.png
class AssetResource {
  /// Creates an object to hold the asset resource’s metadata.
  const AssetResource(this.assetName, {this.packageName});

  /// The name of the main asset from the set of asset resources to choose from.
  final String assetName;

  /// The name of the package from which the asset resource is included.
  final String? packageName;

  /// The name used to generate the key to obtain the asset resource. For local assets
  /// this is [assetName], and for assets from packages the [assetName] is
  /// prefixed 'packages/<package_name>/'.
  String get keyName =>
      packageName == null ? assetName : "packages/$packageName/$assetName";

  /// The file basename of the asset resource.
  String get fileBasename {
    final basename = path.basename(assetName);
    return basename;
  }

  /// The no extension file basename of the asset resource.
  String get fileBasenameNoExtension {
    final basenameWithoutExtension = path.basenameWithoutExtension(assetName);
    return basenameWithoutExtension;
  }

  /// The file extension name of the asset resource.
  String get fileExtname {
    final extension = path.extension(assetName);
    return extension;
  }

  /// The directory path name of the asset resource.
  String get fileDirname {
    var dirname = assetName;
    if (packageName != null) {
      final packageStr = "packages/$packageName/";
      dirname = dirname.replaceAll(packageStr, "");
    }
    final filenameStr = "$fileBasename/";
    dirname = dirname.replaceAll(filenameStr, "");
    return dirname;
  }
}

// ignore: camel_case_types
class _R_Image_AssetResource {
  const _R_Image_AssetResource();

  /// asset: lib/assets/images/deaths.png
  // ignore: non_constant_identifier_names
  final deaths =
      const AssetResource("assets/images/deaths.png", packageName: R.package);

  /// asset: lib/assets/images/distance.png
  // ignore: non_constant_identifier_names
  final distance =
      const AssetResource("assets/images/distance.png", packageName: R.package);

  /// asset: lib/assets/images/ic_launcher.png
  // ignore: non_constant_identifier_names
  final ic_launcher = const AssetResource("assets/images/ic_launcher.png",
      packageName: R.package);

  /// asset: lib/assets/images/mask.png
  // ignore: non_constant_identifier_names
  final mask =
      const AssetResource("assets/images/mask.png", packageName: R.package);

  /// asset: lib/assets/images/newTests.png
  // ignore: non_constant_identifier_names
  final newTests =
      const AssetResource("assets/images/newTests.png", packageName: R.package);

  /// asset: lib/assets/images/recovered.png
  // ignore: non_constant_identifier_names
  final recovered = const AssetResource("assets/images/recovered.png",
      packageName: R.package);

  /// asset: lib/assets/images/sick.png
  // ignore: non_constant_identifier_names
  final sick =
      const AssetResource("assets/images/sick.png", packageName: R.package);

  /// asset: lib/assets/images/tests.png
  // ignore: non_constant_identifier_names
  final tests =
      const AssetResource("assets/images/tests.png", packageName: R.package);

  /// asset: lib/assets/images/wash.png
  // ignore: non_constant_identifier_names
  final wash =
      const AssetResource("assets/images/wash.png", packageName: R.package);
}

// ignore: camel_case_types
class _R_Svg_AssetResource {
  const _R_Svg_AssetResource();

  /// asset: lib/assets/images/hands.svg
  // ignore: non_constant_identifier_names
  final hands =
      const AssetResource("assets/images/hands.svg", packageName: R.package);

  /// asset: lib/assets/images/keep.svg
  // ignore: non_constant_identifier_names
  final keep =
      const AssetResource("assets/images/keep.svg", packageName: R.package);

  /// asset: lib/assets/images/stay.svg
  // ignore: non_constant_identifier_names
  final stay =
      const AssetResource("assets/images/stay.svg", packageName: R.package);

  /// asset: lib/assets/images/wear.svg
  // ignore: non_constant_identifier_names
  final wear =
      const AssetResource("assets/images/wear.svg", packageName: R.package);
}

// ignore: camel_case_types
class _R_Text_AssetResource {
  const _R_Text_AssetResource();
}

/// This `_R_Image` class is generated and contains references to static non-svg type image asset resources.
// ignore: camel_case_types
class _R_Image {
  const _R_Image();

  final asset = const _R_Image_AssetResource();

  /// asset: lib/assets/images/deaths.png
  // ignore: non_constant_identifier_names
  AssetImage deaths() {
    return AssetImage(asset.deaths.keyName);
  }

  /// asset: lib/assets/images/distance.png
  // ignore: non_constant_identifier_names
  AssetImage distance() {
    return AssetImage(asset.distance.keyName);
  }

  /// asset: lib/assets/images/ic_launcher.png
  // ignore: non_constant_identifier_names
  AssetImage ic_launcher() {
    return AssetImage(asset.ic_launcher.keyName);
  }

  /// asset: lib/assets/images/mask.png
  // ignore: non_constant_identifier_names
  AssetImage mask() {
    return AssetImage(asset.mask.keyName);
  }

  /// asset: lib/assets/images/newTests.png
  // ignore: non_constant_identifier_names
  AssetImage newTests() {
    return AssetImage(asset.newTests.keyName);
  }

  /// asset: lib/assets/images/recovered.png
  // ignore: non_constant_identifier_names
  AssetImage recovered() {
    return AssetImage(asset.recovered.keyName);
  }

  /// asset: lib/assets/images/sick.png
  // ignore: non_constant_identifier_names
  AssetImage sick() {
    return AssetImage(asset.sick.keyName);
  }

  /// asset: lib/assets/images/tests.png
  // ignore: non_constant_identifier_names
  AssetImage tests() {
    return AssetImage(asset.tests.keyName);
  }

  /// asset: lib/assets/images/wash.png
  // ignore: non_constant_identifier_names
  AssetImage wash() {
    return AssetImage(asset.wash.keyName);
  }
}

/// This `_R_Svg` class is generated and contains references to static svg type image asset resources.
// ignore: camel_case_types
class _R_Svg {
  const _R_Svg();

  final asset = const _R_Svg_AssetResource();

  /// asset: lib/assets/images/hands.svg
  // ignore: non_constant_identifier_names
  AssetSvg hands({required double width, required double height}) {
    final imageProvider =
        AssetSvg(asset.hands.keyName, width: width, height: height);
    return imageProvider;
  }

  /// asset: lib/assets/images/keep.svg
  // ignore: non_constant_identifier_names
  AssetSvg keep({required double width, required double height}) {
    final imageProvider =
        AssetSvg(asset.keep.keyName, width: width, height: height);
    return imageProvider;
  }

  /// asset: lib/assets/images/stay.svg
  // ignore: non_constant_identifier_names
  AssetSvg stay({required double width, required double height}) {
    final imageProvider =
        AssetSvg(asset.stay.keyName, width: width, height: height);
    return imageProvider;
  }

  /// asset: lib/assets/images/wear.svg
  // ignore: non_constant_identifier_names
  AssetSvg wear({required double width, required double height}) {
    final imageProvider =
        AssetSvg(asset.wear.keyName, width: width, height: height);
    return imageProvider;
  }
}

/// This `_R_Text` class is generated and contains references to static text asset resources.
// ignore: camel_case_types
class _R_Text {
  const _R_Text();

  final asset = const _R_Text_AssetResource();
}

/// This `_R_FontFamily` class is generated and contains references to static font asset resources.
// ignore: camel_case_types
class _R_FontFamily {
  const _R_FontFamily();

  /// font family: CV
  // ignore: non_constant_identifier_names
  final cV = "CV";
}
